### ISSUE TITLE
500 errors for Store.all()

### ISSUE THREAD

**Issue by simonkreuz** [bigcommerce/bigcommerce-api-python#13]
We see 500 errros for some of our requests. Below is the stack trace we see in python (you can see that accessing Store.all() triggers the error). Any help would be much appreciated.

```
Task bigcommerce_app.helpers.
import_orders.import_orders with id 251b17ba-0bea-4f7e-964a-2d262115905c raised exception:
"ServerException('500 Internal Server Error @ store: An error has occurred.',)"


Task was called with args: (<APIUser: API User XXX@yahoo.com>,) kwargs: {}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py", line 238, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py", line 416, in __protected_call__
    return self.run(*args, **kwargs)
  File "./bigcommerce_app/helpers/import_orders.py", line 18, in import_orders
    return get_unimported_orders(client, apiuser)
  File "./bigcommerce_app/helpers/import_orders.py", line 44, in get_unimported_orders
    storeinfo = get_storeinfo(client)
  File "./bigcommerce_app/helpers/import_orders.py", line 22, in get_storeinfo
    store = client.Store.all()
  File "/app/.heroku/python/lib/python2.7/site-packages/bigcommerce/api.py", line 55, in <lambda>
    return lambda *args, **kwargs: (getattr(self.resource_class, item))(*args, connection=self.connection, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/bigcommerce/resources/base.py", line 82, in all
    request = cls._make_request('GET', cls.resource_name, connection, params=params)
  File "/app/.heroku/python/lib/python2.7/site-packages/bigcommerce/resources/base.py", line 42, in _make_request
    return connection.make_request(method, url, data, params, headers)
  File "/app/.heroku/python/lib/python2.7/site-packages/bigcommerce/connection.py", line 120, in make_request
    return self._handle_response(url, response)
  File "/app/.heroku/python/lib/python2.7/site-packages/bigcommerce/connection.py", line 154, in _handle_response

    raise ServerException("%d %s @ %s: %s" % (res.status_code, res.reason, url, res.content), res)
ServerException: 500 Internal Server Error @ store: An error has occurred.
```

**Comment by bookernath** [comment]
Hi Simon,

Are you still seeing these?

I started working with this library after your post, but I haven't seen any pattern of 500s on the store resource in the time I've been using it. It may have been a bug with the API itself which has since been fixed.

**Comment by simonkreuz** [comment]
That was 2 years back - can be closed.
